@WebService_HostAddress = https://localhost:5001

# INFO: Replace with a valid JWT token after login
@Authentication_Token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsInVpZCI6IjU1IiwiZXhwIjoxNzY1MjgyNjY3fQ.c9wT782ouskDprjirAnTs5Y50PfQvW7la7hFYxGVz8iKqeFOzVV5r-Agx9sPXdojYyojN43hyifUiifzYsteKQ

### Health Check ###

GET {{WebService_HostAddress}}/api/health
Accept: application/json

### Authentication Tests ###

### Create a new user (Sign up)

POST {{WebService_HostAddress}}/api/v2/auth/signup
Content-Type: application/json

{
  "name": "Test User",
  "username": "testuser3",
  "password": "password12311",
  "email": "anothermail@mail.com"
}

### Login with the created user

POST {{WebService_HostAddress}}/api/v2/auth/login
Content-Type: application/json

{
  "username": "testuser2",
  "password": "password12311"
}

### User Tests ###

### Get user
GET {{WebService_HostAddress}}/api/v2/users/55
Accept: application/json

### Get user bookmarks
GET {{WebService_HostAddress}}/api/v2/users/55/bookmarks
Accept: application/json

### Get user bookmark by pageID
GET {{WebService_HostAddress}}/api/v2/users/55/bookmarks/1
Accept: application/json

### POST user bookmark
POST {{WebService_HostAddress}}/api/v2/users/55/bookmarks
Authorization: Bearer {{Authentication_Token}}
Content-Type: application/json

{
  "PageId": 1
}

### DELETE user bookmark
DELETE {{WebService_HostAddress}}/api/v2/users/55/bookmarks/1
Authorization: Bearer {{Authentication_Token}}

### Get user ratings
GET {{WebService_HostAddress}}/api/v2/users/55/ratings
Accept: application/json

### Get user rating by TitleID
GET {{WebService_HostAddress}}/api/v2/users/55/ratings/tt0052520
Accept: application/json

### POST user rating
POST {{WebService_HostAddress}}/api/v2/users/55/ratings
Authorization: Bearer {{Authentication_Token}}
Content-Type: application/json

{
  "TitleId": "tt0052520",
  "Rating": 9
}

### PUT user rating (update existing)
PUT {{WebService_HostAddress}}/api/v2/users/55/ratings/tt0052520
Authorization: Bearer {{Authentication_Token}}
Content-Type: application/json

{
  "Rating": 8
}

### DELETE user rating
DELETE {{WebService_HostAddress}}/api/v2/users/55/ratings/tt0052520
Authorization: Bearer {{Authentication_Token}}

### Titles Tests ###

### Get Title by ID
GET {{WebService_HostAddress}}/api/v2/titles/tt0052520
Accept: application/json

### Get Titles (paged by default)
GET {{WebService_HostAddress}}/api/v2/titles
Accept: application/json

### Get Titles (page 2, page size 5)
GET {{WebService_HostAddress}}/api/v2/titles?pageNumber=2&pageSize=5
Accept: application/json

### Get Title ratings
GET {{WebService_HostAddress}}/api/v2/titles/tt0052520/ratings
Accept: application/json

### Get Title's Individuals
GET {{WebService_HostAddress}}/api/v2/titles/tt0052520/individuals
Accept: application/json

### Individuals Tests ###

### Get Individual by ID
GET {{WebService_HostAddress}}/api/v2/individuals/nm0000199
Accept: application/json

### Get Individuals (paged by default)
GET {{WebService_HostAddress}}/api/v2/individuals
Accept: application/json

### Get Individuals (page 2, page size 5)
GET {{WebService_HostAddress}}/api/v2/individuals?pageNumber=2&pageSize=5
Accept: application/json

### Get Individual's Titles
GET {{WebService_HostAddress}}/api/v2/individuals/nm0000199/titles
Accept: application/json
